/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import javax.swing.JOptionPane;
import koneksi.konekmenu;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author My Computer
 */
public class menumakanan extends javax.swing.JFrame {

    /**
     * Creates new form menumakanan
     */
    public menumakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxkuenastar = new javax.swing.JCheckBox();
        cbxkuebakpia = new javax.swing.JCheckBox();
        cbxkuebolu = new javax.swing.JCheckBox();
        cbxrotibluder = new javax.swing.JCheckBox();
        cbxbakpao = new javax.swing.JCheckBox();
        cbxkuebrownis = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtjumlah1 = new javax.swing.JTextField();
        txtjumlah3 = new javax.swing.JTextField();
        txtjumlah4 = new javax.swing.JTextField();
        txtjumlah6 = new javax.swing.JTextField();
        txtjumlah7 = new javax.swing.JTextField();
        txtjumlah8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jmlbayar = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtkembalian = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtpesan = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("MENU MAKANAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(41, 45, 125, 31);

        jLabel2.setText("HARGA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(192, 53, 67, 14);

        jLabel3.setText("JUMLAH :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(277, 53, 60, 14);

        cbxkuenastar.setText("KUE NASTAR");
        getContentPane().add(cbxkuenastar);
        cbxkuenastar.setBounds(41, 94, 110, 23);

        cbxkuebakpia.setText("KUE BAKPIA");
        getContentPane().add(cbxkuebakpia);
        cbxkuebakpia.setBounds(41, 135, 91, 23);

        cbxkuebolu.setText("KUE BOLU");
        getContentPane().add(cbxkuebolu);
        cbxkuebolu.setBounds(41, 181, 81, 23);

        cbxrotibluder.setText("ROTI BLUDER");
        getContentPane().add(cbxrotibluder);
        cbxrotibluder.setBounds(40, 230, 105, 23);

        cbxbakpao.setText("BAKPAO");
        getContentPane().add(cbxbakpao);
        cbxbakpao.setBounds(40, 280, 81, 23);

        cbxkuebrownis.setText("KUE BROWNIS");
        getContentPane().add(cbxkuebrownis);
        cbxkuebrownis.setBounds(40, 330, 120, 23);

        jLabel4.setText("Rp. 60.000");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(192, 98, 70, 20);

        jLabel5.setText("Rp. 20.000");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(192, 139, 80, 20);

        jLabel6.setText("Rp.35.000");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(192, 175, 70, 30);

        jLabel7.setText("Rp. 25.000");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 224, 70, 30);

        jLabel8.setText("Rp. 10.000");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 274, 70, 30);

        jLabel9.setText("Rp. 30.000");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 320, 70, 40);
        getContentPane().add(txtjumlah1);
        txtjumlah1.setBounds(280, 90, 60, 30);
        getContentPane().add(txtjumlah3);
        txtjumlah3.setBounds(280, 140, 60, 30);
        getContentPane().add(txtjumlah4);
        txtjumlah4.setBounds(280, 180, 60, 30);
        getContentPane().add(txtjumlah6);
        txtjumlah6.setBounds(280, 230, 60, 30);
        getContentPane().add(txtjumlah7);
        txtjumlah7.setBounds(280, 280, 60, 30);

        txtjumlah8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlah8ActionPerformed(evt);
            }
        });
        getContentPane().add(txtjumlah8);
        txtjumlah8.setBounds(280, 330, 60, 30);

        jLabel10.setText("MENU YANG DIPESAN :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(437, 53, 138, 14);

        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(587, 176, 99, 33);

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(807, 176, 73, 33);

        jButton3.setText("BAYAR : ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 340, 89, 23);
        getContentPane().add(txttotal);
        txttotal.setBounds(590, 250, 301, 55);
        getContentPane().add(jmlbayar);
        jmlbayar.setBounds(590, 330, 300, 40);

        jButton4.setText("SIMPAN ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 460, 90, 23);
        getContentPane().add(txtkembalian);
        txtkembalian.setBounds(590, 400, 310, 40);

        jLabel11.setText("TOTAL HARGA :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(480, 260, 90, 14);

        txtpesan.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtpesan.setRows(5);
        getContentPane().add(txtpesan);
        txtpesan.setBounds(580, 40, 310, 130);

        setSize(new java.awt.Dimension(942, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String tampil;
        tampil = "";
        int bayar = 0;
        if(cbxkuenastar.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah1.getText());
            int total;
            total=jumlah*60000;
            bayar=bayar+total;
            tampil +=cbxkuenastar.getText()+" Rp.60000"+" x "+jumlah+" = "+total+"\n";
        
        }if(cbxkuebakpia.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah3.getText());
            int total;
            total=jumlah*20000;
            bayar=bayar+total;
            tampil +=cbxkuebakpia.getText()+" Rp.20000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxkuebolu.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah4.getText());
            int total;
            total=jumlah*35000;
            bayar=bayar+total;
            tampil +=cbxkuebolu.getText()+" Rp.35000"+" x "+jumlah+" = "+total+"\n";
        
        }if(cbxrotibluder.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah6.getText());
            int total;
            total=jumlah*25000;
            bayar=bayar+total;
            tampil +=cbxrotibluder.getText()+" Rp.25000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxbakpao.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah7.getText());
            int total;
            total=jumlah*10000;
            bayar=bayar+total;
            tampil +=cbxbakpao.getText()+" Rp.10000"+" x "+jumlah+" = "+total+"\n";
        }if(cbxkuebrownis.isSelected()){
            int jumlah=Integer.parseInt(txtjumlah8.getText());
            int total;
            total=jumlah*30000;
            bayar=bayar+total;
            tampil +=cbxkuebrownis.getText()+" Rp.30000"+" x "+jumlah+" = "+total+"\n";
        }
        txtpesan.setText(tampil);
         txttotal.setText(""+bayar);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtjumlah8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlah8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjumlah8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
double byr = Double.parseDouble(jmlbayar.getText());
        double hg = Double.parseDouble(txttotal.getText());
        double kembali = byr - hg;        
txtkembalian.setText(""+kembali);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      konekmenu ip = new konekmenu();
        ip.jumlahnastar = txtjumlah1.getText();
        ip.jumlahbakpia = txtjumlah3.getText();
        ip.jumlahbolu = txtjumlah4.getText();
        ip.jumlahbluder = txtjumlah6.getText();
        ip.jumlahbakpao = txtjumlah7.getText();
        ip.jumlahbrownies = txtjumlah8.getText();
        ip.totalharga = txttotal.getText();
        ip.bayar = jmlbayar.getText();
        ip.kembali = txtkembalian.getText();
        try {
            ip.simpan();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
// TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        txtjumlah1.setText("");
       
        txtjumlah3.setText("");
        txtjumlah4.setText("");
        
        txtjumlah6.setText("");
        txtjumlah7.setText("");
        txtjumlah8.setText("");
        txtpesan.setText(""); 
        txttotal.setText("");
        jmlbayar.setText("");
        txtkembalian.setText("");
    
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menumakanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menumakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxbakpao;
    private javax.swing.JCheckBox cbxkuebakpia;
    private javax.swing.JCheckBox cbxkuebolu;
    private javax.swing.JCheckBox cbxkuebrownis;
    private javax.swing.JCheckBox cbxkuenastar;
    private javax.swing.JCheckBox cbxrotibluder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jmlbayar;
    private javax.swing.JTextField txtjumlah1;
    private javax.swing.JTextField txtjumlah3;
    private javax.swing.JTextField txtjumlah4;
    private javax.swing.JTextField txtjumlah6;
    private javax.swing.JTextField txtjumlah7;
    private javax.swing.JTextField txtjumlah8;
    private javax.swing.JTextField txtkembalian;
    private java.awt.TextArea txtpesan;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}

